function volplot(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, CDATA1, ZDATA2)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata
%  ZDATA2:  surface zdata

%  Auto-generated by MATLAB on 19-May-2015 04:11:39

% Create figure
figure1 = figure('Colormap',...
    [1 1 0.8;1 0.929411764705882 0.627450980392157;0.996078431372549 0.850980392156863 0.462745098039216;0.996078431372549 0.8 0.36078431372549;0.996078431372549 0.698039215686274 0.298039215686275;0.988235294117647 0.305882352941176 0.164705882352941;0.941176470588235 0.231372549019608 0.125490196078431;0.890196078431373 0.101960784313725 0.109803921568627;0.741176470588235 0 0.149019607843137;0.501960784313725 0 0.149019607843137]);

% Create axes
axes1 = axes('Parent',figure1,'ZTickLabel',{'30%','40%','50%','60%','70%',},...
    'ZTick',[0.3  0.4  0.5  0.6  0.7],...
    'YTick',[0.8 0.9 1 1.1 1.2],...
    'XTick',[0.1 0.3 0.5 0.7 1],...
    'CLim',[0.0970594512333223 0.344248641727664],...
    'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.1 1]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.8 1.2]);
%% Uncomment the following line to preserve the Z-limits of the axes
zlim(axes1,[0.3 0.7]);
view(axes1,[-70 15]);
grid(axes1,'on');
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,...
    'FaceAlpha',0.9,...
    'FaceColor',[0 0.47843137254902 0.752941176470588],...
    'EdgeColor',[0.1 0.1 0.1]);

% Create xlabel
xlabel('Maturity','Margin',2,'FontSize',14);

% Create ylabel
ylabel('Money-ness','Margin',2,'FontSize',14);

% Create zlabel
zlabel('Call Option Implied Volatility (%)','Margin',2,'FontSize',14);
% % 
% % Create legend
% % legend1 = legend(axes1,'show');
% % set(legend1,...
% %     'Position',[0.256920903954802 0.573835696353542 0.286158192090395 0.24901185770751],...
% %     'FontSize',14,...
% %     'EdgeColor',[0 0 0]);
hold on;
