function createccffigure(X1, YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 18-Sep-2015 15:12:35

% Create figure
figure1 = figure;
set(0,'defaulttextinterpreter','latex')

% Create subplot
subplot1 = subplot(1,3,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'on');

% Create xlabel
xlabel({'$s_1$'});

% Create title
title({'$\phi([s_1,0,0],X^\star,\Delta;\theta)$'});

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','\Re [\phi]');
set(plot1(2),'DisplayName','\Im [\phi]');

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Location','southeast',...
    'FontSize',9);

% Create subplot
subplot2 = subplot(1,3,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'on');

% Create xlabel
xlabel({'$s_2$'});

% Create title
title({'$\phi([0,s_2,0],X^\star,\Delta;\theta)$'});

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2);
set(plot2(1),'DisplayName','\Re [\phi]');
set(plot2(2),'DisplayName','\Im [\phi]');

% Create legend
legend2 = legend(subplot2,'show');
set(legend2,...
    'Location','southeast',...
    'FontSize',9);

% Create subplot
subplot3 = subplot(1,3,3,'Parent',figure1);
box(subplot3,'on');
hold(subplot3,'on');

% Create xlabel
xlabel({'$s_3$'});

% Create title
title({'$\phi([0,0,s_3],X^\star,\Delta;\theta)$'});

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',subplot3);
set(plot3(1),'DisplayName','\Re [\phi]');
set(plot3(2),'DisplayName','\Im [\phi]');

% Create legend
legend3 = legend(subplot3,'show');
set(legend3,...
    'Location','southeast',...
    'FontSize',9);

